/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-12-21 00:34:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insert_005fmember_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원 가입</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<script src=\"resources/js/header.js\"></script>\r\n");
      out.write("<script src=\"resources/js/member_check.js\"></script>\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/main_form_no_slide.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/insert_form.css\">\r\n");
      out.write("<script>\r\n");
      out.write("\tvar kind='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kind}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"header\">\t\r\n");
      out.write("\t<div class=\"header_wrap\">\r\n");
      out.write("\t\t<div class=\"logo_box\"><a href=\"index.jsp\"><img src=\"resources/img/logo.png\"  width=\"300px\" height=\"85px\"alt=\"\" /></a></div>\r\n");
      out.write("\t\t<div class=\"nav_box\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><button id=\"login_btn\" onclick=\"\" ><img src=\"resources/img/user_icon.png\" width=\"45px\" height=\"45px\" alt=\"\" /></button></li>\r\n");
      out.write("\t\t\t\t<li><button id=\"news_btn\" onclick=\"\" ><img src=\"resources/img/news.png\" width=\"60px\" height=\"60px\" alt=\"\" /></button></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"member_box\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("\t<div class=\"insert_box\">\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t<h2>회원가입</h2>\r\n");
      out.write("\t\t<hr />\r\n");
      out.write("\t\t<div class=\"insert_nav\">\r\n");
      out.write("\t\t\t<button class=\"mem active\">일반 회원</button>\t\r\n");
      out.write("\t\t\t<button class=\"com_mem\">사업자 회원</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"insert_form\">\r\n");
      out.write("\t\t\t<form id=\"insert_member\" action=\"insert_member.do\" method=\"get\" onsubmit=\"return form_check(); \">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"id\">아이디</label>\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"id\" id=\"id\" placeholder=\"6-30 자리 / 영어 대소문자와 숫자만 사용 가능합니다.\" oninput=\"check_id();\"/>\r\n");
      out.write("\t\t\t\t\t<div id=\"err_box\" class=\"member_id_check\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"password\">비밀번호</label>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" name=\"password\" id=\"password\" placeholder=\"6-30 자리 / 영어 대소문자와 숫자만 사용 가능합니다.\"/>\r\n");
      out.write("\t\t\t\t\t<div id=\"err_box\" class=\"member_pwd_check\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"password_chk\">비밀번호 확인</label>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" id=\"password_chk\" />\r\n");
      out.write("\t\t\t\t\t<div id=\"err_box\" class=\"member_pwd_check_2\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"name\">이름</label>\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"name\" id=\"name\" maxlength=\"5\" placeholder=\"최대 5자까지 입력 가능합니다.\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"birth_wrap\">\r\n");
      out.write("\t\t\t\t\t<label for=\"yy\">생년월일</label>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"yy\" maxlength=\"4\" placeholder=\"년(4자)\"/>\r\n");
      out.write("\t\t\t\t\t<select name=\"\" id=\"mm\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"01\">1월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"02\">2월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"03\">3월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"04\">4월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"05\">5월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"06\">6월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"07\">7월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"08\">8월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"09\">9월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"10\">10월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"11\">11월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"12\">12월</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"dd\" maxlength=\"2\" placeholder=\"일\"/>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" class=\"birth\" name=\"birth\" value=\"\"/>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"gender\">성별</label>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<select name=\"gender\" id=\"gender\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">성별</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">남자</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">여자</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"email\">본인 확인 이메일</label>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=email id=\"email\" />\r\n");
      out.write("\t\t\t\t\t<div id=\"err_box\" class=\"member_email_check\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"phone\">휴대전화</label>\r\n");
      out.write("\t\t\t\t\t<select  id=\"country_code\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"+82\">대한민국 +82</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"+1\">미국/캐나다 +1</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"+64\">뉴질랜드 +64</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"+49\">독일 +49</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"+44\">영국 +44</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"+55\">브라질 +55</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"+82\">대한민국 +82</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"+90\">터키 +90</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"+63\">필리핀 +63</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"phone_number\" maxlength=\"11\" placeholder=\"전화번호 입력\"/> \r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" class=\"phone\" name=\"phone\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t<div id=\"err_box\" class=\"member_phone_number_check\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"addr_wrap\">\r\n");
      out.write("\t\t\t\t\t<label for=\"address\">주소</label>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"address_1\" placeholder=\"우편번호\" /><input type=\"button\" onclick=\"find_address()\" value=\"우편번호 찾기\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"address_2\" placeholder=\"주소\" /><input type=\"text\" id=\"address_3\" placeholder=\"상세주소\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" class=\"address\" name=\"address\" value=\"\"  />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input class=\"member_submit\" type=\"submit\" value=\"회원가입\" />\r\n");
      out.write("\t\t\t</form>\t\r\n");
      out.write("\t\t\t<form id=\"insert_com_member\" action=\"insert_com_member.do\" method=\"get\" onsubmit=\"return com_form_check();\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"id\">아이디</label>\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"id\" id=\"com_id\" placeholder=\"6-30 자리 / 영어 대소문자와 숫자만 사용 가능합니다.\" oninput=\"check_com_id();\"/>\r\n");
      out.write("\t\t\t\t\t<div id=\"err_box\" class=\"com_member_id_check\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"password\">비밀번호</label>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" name=\"password\" id=\"com_password\" placeholder=\"6-30 자리 / 영어 대소문자와 숫자만 사용 가능합니다.\"/>\r\n");
      out.write("\t\t\t\t\t<div id=\"err_box\" class=\"com_member_pwd_check\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"com_password_chk\">비밀번호 확인</label>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" id=\"com_password_chk\" />\r\n");
      out.write("\t\t\t\t\t<div id=\"err_box\" class=\"com_member_pwd_check_2\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"brand_name\">브랜드명(영문)</label>\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"brand_name\" id=\"brand_name\" />\r\n");
      out.write("\t\t\t\t\t<div id=\"err_box\" class=\"member_brand_check\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"brand_name_ko\">브랜드명(한글)</label>\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"brand_name_ko\" id=\"brand_name_ko\" />\r\n");
      out.write("\t\t\t\t\t<div id=\"err_box\" class=\"member_brand_ko_check\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"reg_num\">사업자 등록번호</label>\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"reg_num\" id=\"reg_num\" />\r\n");
      out.write("\t\t\t\t\t<div id=\"err_box\" class=\"member_reg_num_check\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"email\">본인 확인 이메일</label>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=email id=\"com_email\" />\r\n");
      out.write("\t\t\t\t\t<div id=\"err_box\" class=\"com_member_email_check\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"phone\">휴대전화</label>\r\n");
      out.write("\t\t\t\t\t<select  id=\"com_country_code\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"+82\">대한민국 +82</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"+1\">미국/캐나다 +1</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"+64\">뉴질랜드 +64</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"+49\">독일 +49</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"+44\">영국 +44</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"+55\">브라질 +55</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"+82\">대한민국 +82</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"+90\">터키 +90</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"+63\">필리핀 +63</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"com_phone_number\" maxlength=\"11\" placeholder=\"전화번호 입력\"/> \r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" class=com_phone\" name=\"phone\" value=\"\"/>\r\n");
      out.write("\t\t\t\t\t<div id=\"err_box\" class=\"member_com_phone_number_check\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"addr_wrap\">\r\n");
      out.write("\t\t\t\t\t<label for=\"address\">주소</label>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"com_address_1\" placeholder=\"우편번호\" /><input type=\"button\" onclick=\"find_address()\" value=\"우편번호 찾기\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"com_address_2\" placeholder=\"주소\" /><input type=\"text\" id=\"com_address_3\" placeholder=\"상세주소\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" class=\"com_address\" name=\"address\" value=\"\"  />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input class=\"member_submit\" type=\"submit\" value=\"회원가입\" />\r\n");
      out.write("\t\t\t</form>\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("\t<h1>푸터ㅓㅓㅓㅓㅓ</h1>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
