/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-12-22 04:06:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.draw_calendar.project.VO.Draw_siteVO;
import com.draw_calendar.project.DAO.Draw_siteDAO;
import com.draw_calendar.project.VO.BrandVO;
import com.draw_calendar.project.service.Brand_service;
import org.springframework.context.support.GenericXmlApplicationContext;
import org.springframework.context.ApplicationContext;

public final class insert_005fitem_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/Project/Draw_calendar/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DrawCalendar/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1605764819572L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.springframework.context.support.GenericXmlApplicationContext");
    _jspx_imports_classes.add("com.draw_calendar.project.VO.Draw_siteVO");
    _jspx_imports_classes.add("com.draw_calendar.project.DAO.Draw_siteDAO");
    _jspx_imports_classes.add("com.draw_calendar.project.service.Brand_service");
    _jspx_imports_classes.add("com.draw_calendar.project.VO.BrandVO");
    _jspx_imports_classes.add("org.springframework.context.ApplicationContext");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	String brand_name = (String)session.getAttribute("brand_name");

	ApplicationContext ctx = new GenericXmlApplicationContext("classpath:root-context.xml");
	Brand_service service = ctx.getBean("brand_service_impl", Brand_service.class);
	BrandVO vo = new BrandVO();
	pageContext.setAttribute("brand_list", service.select_brand_list(vo));
	
	Draw_siteDAO dao = ctx.getBean("draw_site_service", Draw_siteDAO.class);
	Draw_siteVO siteVO = new Draw_siteVO();
	pageContext.setAttribute("draw_site", dao.select_draw_site_list(siteVO));

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>상품 등록</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<script src=\"resources/js/header.js\"></script>\r\n");
      out.write("<script src=\"resources/js/insert_item.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/main_form_no_slide.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/insert_form_item.css\">\r\n");
      out.write("<script>\r\n");
      out.write("\tvar kind='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kind}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"header\">\t\r\n");
      out.write("\t<div class=\"header_wrap\">\r\n");
      out.write("\t\t<div class=\"logo_box\"><a href=\"index.jsp\"><img src=\"resources/img/logo.png\"  width=\"300px\" height=\"85px\"alt=\"\" /></a></div>\r\n");
      out.write("\t\t<div class=\"nav_box\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><button id=\"login_btn\" onclick=\"\" ><img src=\"resources/img/user_icon.png\" width=\"45px\" height=\"45px\" alt=\"\" /></button></li>\r\n");
      out.write("\t\t\t\t<li><button id=\"news_btn\" onclick=\"\" ><img src=\"resources/img/news.png\" width=\"60px\" height=\"60px\" alt=\"\" /></button></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("\t<div class=\"member_box\"></div>\r\n");
      out.write("\t<div class=\"insert_box\">\r\n");
      out.write("\t\t<br />\r\n");
      out.write("\t\t<h2>상품 등록</h2>\r\n");
      out.write("\t\t<hr />\r\n");
      out.write("\t\t<div class=\"insert_form\">\r\n");
      out.write("\t\t\t<form id=\"insert_item\" action=\"insert_item.do\" method=\"get\" >\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"model_name\">모델명</label>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name = \"model_name\" id=\"model_name\" />\r\n");
      out.write("\t\t\t\t\t<div id=\"err_box\" class=\"member_pwd_check_2\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"model_code\">모델 코드</label>\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"model_code\" id=\"model_code\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"item_img\">이미지</label>\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"item_img\" id=\"item_img\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"price\">가격</label>\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"price\" id=\"price\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"s_size\">사이즈</label>\t\t\t\r\n");
      out.write("\t\t\t\t\t<select name=\"s_size\" id=\"s_size\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"ALL\">공용</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"MAN\">남성용</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"WOMAN\">여성용</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"KID\">유아용</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"collaboration\">콜라보</label>\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"collaboration\" id=\"collaboration\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id =\"date_wrap\" class=\"draw_date_wrap\">\r\n");
      out.write("\t\t\t\t\t<label for=\"draw_mm\">응모일</label>\r\n");
      out.write("\t\t\t\t\t<select name=\"\" id=\"draw_mm\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">1월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">2월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">3월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">4월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">5월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"6\">6월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"7\">7월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"8\">8월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"9\">9월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"10\">10월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"11\">11월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"12\">12월</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"draw_dd\" maxlength=\"2\" placeholder=\"1 - 31일\"/>\r\n");
      out.write("\t\t\t\t\t<select name=\"\" id=\"draw_tt\" >\r\n");
      out.write("\t\t\t\t\t\t<option value=\"9\">오전 9시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"10\">10시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"11\">11시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"12\">12시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"13\">오후 1시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"14\">2시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"15\">3시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"16\">4시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"17\">5시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"18\">6시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"19\">7시</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" class=\"draw_date\" name=\"draw_date\" value=\"\"/>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t \t<div id =\"date_wrap\" class=\"announce_date_wrap\">\r\n");
      out.write("\t\t\t\t\t<label for=\"mm\">발표일</label>\r\n");
      out.write("\t\t\t\t\t<select name=\"\" id=\"announce_mm\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">1월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">2월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">3월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">4월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">5월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"6\">6월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"7\">7월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"8\">8월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"9\">9월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"10\">10월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"11\">11월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"12\">12월</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"announce_dd\" maxlength=\"2\" placeholder=\"1 - 31일\"/>\r\n");
      out.write("\t\t\t\t\t<select name=\"\" id=\"announce_tt\" >\r\n");
      out.write("\t\t\t\t\t\t<option value=\"9\">오전 9시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"10\">10시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"11\">11시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"12\">12시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"13\">오후 1시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"14\">2시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"15\">3시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"16\">4시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"17\">5시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"18\">6시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"19\">7시</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" class=\"announce_date\" name=\"announce_date\" value=\"\"/>\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t<div id =\"date_wrap\" class=\"purchase_date_wrap\">\r\n");
      out.write("\t\t\t\t\t<label for=\"mm\">구매일</label>\r\n");
      out.write("\t\t\t\t\t<select name=\"\" id=\"purchase_mm\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">1월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">2월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">3월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">4월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">5월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"6\">6월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"7\">7월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"8\">8월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"9\">9월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"10\">10월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"11\">11월</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"12\">12월</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"purchase_dd\" maxlength=\"2\" placeholder=\"1 - 31일\"/>\r\n");
      out.write("\t\t\t\t\t<select name=\"\" id=\"purchase_tt\" >\r\n");
      out.write("\t\t\t\t\t\t<option value=\"9\">오전 9시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"10\">10시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"11\">11시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"12\">12시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"13\">오후 1시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"14\">2시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"15\">3시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"16\">4시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"17\">5시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"18\">6시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"19\">7시</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" class=\"purchase_date\" name=\"purchase_date\" value=\"\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"draw_site\">\r\n");
      out.write("\t\t\t\t\t<label for=\"site_code\">구매처</label>\t\t\t\r\n");
      out.write("\t\t\t\t\t<select class=\"site_code_1\">\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input type=\"button\" onclick=\"add_draw_site()\" value=\"사이트 추가\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" class=\"draw_site\" name=\"site_code\" value=\"\" />\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name =\"rank\" value=\"10\"/>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"reg_management\" value=\"1\" />\r\n");
      out.write("\t\t\t\t<input class=\"item_submit\" type=\"submit\" value=\"상품 등록\" />\r\n");
      out.write("\t\t\t</form>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("\t<h1>푸터ㅓㅓㅓㅓㅓ</h1>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar i = 2;\r\n");
      out.write("\tconst add_draw_site = function() {\r\n");
      out.write("\t\tvar html = '<select class=\"site_code_'+i+'\">';\r\n");
      out.write("\t\thtml += '");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\thtml += '</select>';\r\n");
      out.write("\t\ti++;\r\n");
      out.write("\t\r\n");
      out.write("\t\t$('#draw_site').append(html);\r\n");
      out.write("\t};\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /insert_item.jsp(56,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kind.equals('company')}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<div>\r\n");
          out.write("\t\t\t\t\t\t<label for=\"brand_code\">브랜드 코드</label>\t\t\r\n");
          out.write("\t\t\t\t\t\t<div class=\"no_change\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${brand_name.toUpperCase().substring(0,2) }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\t\r\n");
          out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"brand_code\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${brand_name.toUpperCase().substring(0,2) }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" />\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t<div>\r\n");
          out.write("\t\t\t\t\t\t<label for=\"brand_name\">브랜드명</label>\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t<div class=\"no_change\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${brand_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\t\r\n");
          out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"brand_name\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${brand_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" />\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /insert_item.jsp(68,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kind.equals('admin')}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<div>\r\n");
          out.write("\t\t\t\t\t\t<label for=\"brand_code\">브랜드 코드</label>\t\t\r\n");
          out.write("\t\t\t\t\t\t<div class=\"no_change\" id =\"brand_code\"></div>\t\r\n");
          out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"brand_code\" class=\"brand_code\" value=\"\"/>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t<div>\r\n");
          out.write("\t\t\t\t\t\t<label for=\"brand_name\">브랜드명</label>\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t<select name=\"brand_name\" id=\"brand_name\">\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("</select>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /insert_item.jsp(77,7) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${brand_list}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /insert_item.jsp(77,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("brand");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${brand.brand_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${brand.brand_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /insert_item.jsp(212,6) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${draw_site}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /insert_item.jsp(212,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("site");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${site.site_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${site.site_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write('-');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${site.site_domain}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /insert_item.jsp(233,11) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${draw_site}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /insert_item.jsp(233,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("site");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("';\r\n");
            out.write("\t\thtml += '<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${site.site_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${site.site_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write('-');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${site.site_domain}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>';\r\n");
            out.write("\t\thtml += '");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }
}
