/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-12-10 07:10:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.springframework.web.servlet.ModelAndView;
import java.util.Comparator;
import java.util.Collections;
import java.util.ArrayList;
import java.util.Map.Entry;
import java.util.List;
import java.util.LinkedHashMap;
import java.util.HashMap;
import java.util.Map;
import java.util.Iterator;
import java.util.Set;
import java.util.HashSet;
import com.draw_calendar.project.VO.ItemsVO;
import com.draw_calendar.project.DAO.ItemsDAO;
import org.springframework.context.support.GenericXmlApplicationContext;
import org.springframework.context.ApplicationContext;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/E:/Project/Draw_calendar/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DrawCalendar/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1605764819572L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.springframework.context.support.GenericXmlApplicationContext");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("org.springframework.context.ApplicationContext");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.util.LinkedHashMap");
    _jspx_imports_classes.add("java.util.HashSet");
    _jspx_imports_classes.add("org.springframework.web.servlet.ModelAndView");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.draw_calendar.project.VO.ItemsVO");
    _jspx_imports_classes.add("java.util.Map.Entry");
    _jspx_imports_classes.add("com.draw_calendar.project.DAO.ItemsDAO");
    _jspx_imports_classes.add("java.util.Comparator");
    _jspx_imports_classes.add("java.util.Collections");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	ApplicationContext ctx = new GenericXmlApplicationContext("classpath:root-context.xml");
	ItemsDAO dao = ctx.getBean("itemsDAO", ItemsDAO.class);
	ItemsVO vo = new ItemsVO();
	
	pageContext.setAttribute("items_list", dao.select_items_list(vo));
	System.out.println(dao.select_items_list(vo));
	
	
	Cookie[] cookies = request.getCookies();
	String[] item_cookie_list = null;
	Map<String, Integer> cookie_brand_cnt = new HashMap<String, Integer>();
	
	if(cookies !=null && cookies.length > 0 ) {
		for(int i = 0; i < cookies.length; i++) {
			System.out.println("쿠키가 있느뇨");
			if ( cookies[i].getName().equals("item_cookie")){
				item_cookie_list = cookies[i].getValue().substring(0,cookies[i].getValue().length()-1).split("/");
				break;
			}
		}
	}
	
	if( item_cookie_list != null){
		for(String list : item_cookie_list){
			if(cookie_brand_cnt.containsKey(list)){
				cookie_brand_cnt.put(list, cookie_brand_cnt.get(list)+1 );
			} else {
				cookie_brand_cnt.put(list, 1);
			}
			
		}
	}
	List<String> brand_rank = new ArrayList<String>();
	List<Entry<String, Integer>> list_entries = new ArrayList<Entry<String, Integer>>(cookie_brand_cnt.entrySet());

	
	Collections.sort(list_entries, new Comparator<Entry<String, Integer>>() {
		
		public int compare(Entry<String, Integer> obj1, Entry<String, Integer> obj2) {
			return obj2.getValue().compareTo(obj1.getValue());
		}
	});
	
	for(int i = 0; i < list_entries.size(); i ++) {
		System.out.println(list_entries.get(i).getKey());
		brand_rank.add(list_entries.get(i).getKey());
	}

	

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>DrawCalendar</title>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("\t$(document).ready(function(){\n");
      out.write("\t\t$(document).on('click', '.go_to_month', function(){\n");
      out.write("\t\t\t$('.the_iframe').attr('src', 'calendar.jsp');\n");
      out.write("\t\t});\n");
      out.write("\t\t$(document).on('click', '.go_to_week', function(){\n");
      out.write("\t\t\t$('.the_iframe').attr('src', 'week.jsp');\n");
      out.write("\t\t});\n");
      out.write("\t\t$(document).on('click', '.go_to_list', function(){\n");
      out.write("\t\t\t$('.the_iframe').attr('src', 'item_list.do');\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("<style>\n");
      out.write("\t#header {\n");
      out.write("\t\tposition : relative;\n");
      out.write("\t\tmax-width: 1250px;\n");
      out.write("\t\tmargin: 0 auto;\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t}\n");
      out.write("\t#container {\n");
      out.write("\t\tposition : relative;\n");
      out.write("\t\tmax-width: 1250px;\n");
      out.write("\t\tmargin: 0 auto;\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t}\n");
      out.write("\tiframe {\n");
      out.write("\t\tposition: relative;\n");
      out.write("\t\tdisplay: block;\n");
      out.write("\t\twidth: 100%;\n");
      out.write("\t\tmin-height:500px;\"\n");
      out.write("\t\toverflow-x: hidden; \n");
      out.write("\t\toverflow: auto;  \n");
      out.write("\t}\n");
      out.write("\t#footer {\n");
      out.write("\t\tposition : relative;\n");
      out.write("\t\tmax-width: 1250px;\n");
      out.write("\t\tmargin: 0 auto;\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.items_section {\n");
      out.write("\t\tposition: relative;\n");
      out.write("\t\tmax-width: 1250px;\n");
      out.write("\t\theight: 350px;\n");
      out.write("\t\tdisplay: flex;\n");
      out.write("\t\toverflow-x: scroll;\n");
      out.write("\t\tpadding: 10px 20px;\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.item-box {\n");
      out.write("\t\tposition: relative;\n");
      out.write("\t\tmin-width: 350px;\n");
      out.write("\t\theight: 300px;\n");
      out.write("\t\tmargin: 10px 50px;\n");
      out.write("\t\tdisplay: flex;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\ta {\n");
      out.write("\t\tdisplay: block;\n");
      out.write("\t\twidth: 400px;\n");
      out.write("\t\ttext-decoration: none;\n");
      out.write("\t\tcolor: black;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t.img_box {\n");
      out.write("\t\tposition: relative;\n");
      out.write("\t\tpadding-top: 100px;\n");
      out.write("\t\twidth: 100px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.text_box {\n");
      out.write("\t\tline-height: 30px;\n");
      out.write("\t\tpadding: 3px 10px;\n");
      out.write("\t}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div id=\"header\">\n");
      out.write("<h1>헤더입니다ㅓㅓㅓㅓㅓ</h1>\n");
      out.write("</div>\n");
      out.write("<div id=\"container\">\n");
      out.write("\t<a href=\"login.jsp\">로그인</a><br />\n");
      out.write("\t<a href=\"insert_all_member.jsp\">회원가입</a><br />\n");
      out.write("\t<div class=\"calendar_wrap\">\n");
      out.write("\t\t<br />\n");
      out.write("\t\t<button class=\"go_to_month\">Month</button>\n");
      out.write("\t\t<button class=\"go_to_week\">Week</button>\n");
      out.write("\t\t<button class=\"go_to_list\">List</button>\n");
      out.write("\t\t<iframe class=\"the_iframe\" src=\"calendar.jsp\" frameborder=\"0\" scrolling=\"no\" onload=\"this.style.height=(this.contentWindow.document.body.scrollHeight+30)+'px';\"></iframe>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"items_section\">\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div id=\"footer\">\n");
      out.write("\n");
      out.write("<h1>푸터ㅓㅓㅓㅓㅓ</h1>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/index.jsp(170,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/index.jsp(170,2) '${ items_list }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ items_list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/index.jsp(170,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("<a href=\"item_detail.do?model_code=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.model_code }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("\t\t\t\t<div class=\"item-box\">\n");
            out.write("\t\t\t\t\t<!-- <form action=\"item_detail.do\" method=\"get\"> -->\n");
            out.write("\t\t\t\t\t\t<div class=\"img_box\">\t\n");
            out.write("\t\t\t\t\t\t\t<img src=\"http://placehold.it/50x50\" alt=\"\" />\n");
            out.write("\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t<div class=\"text_box\">\n");
            out.write("\t\t\t\t\t\t\t<h3>모델명 : ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.model_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h3>\n");
            out.write("\t\t\t\t\t\t\t<p>브랜드 : ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.brand_code }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\n");
            out.write("\t\t\t\t\t\t\t<p>가격 : ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\n");
            out.write("\t\t\t\t\t\t\t<p>응모일 : ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.draw_date }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\n");
            out.write("\t\t\t\t\t\t\t<!-- <input type=\"submit\" value=\"상세보기\" /> -->\n");
            out.write("\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t<!-- </form> -->\n");
            out.write("\t\t\t\t</div>\n");
            out.write("\t\t\t</a>\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
